sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username:
    password:

  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:

  redis:
    host: localhost
    port: 6379
    database: 10

  wechat:
    appid:
    secret:
    notifyUrl: http://713b8e1.r33.cpolar.top/notify/paySuccess
    refundNotifyUrl: http://713b8e1.r33.cpolar.top/notify/refundSuccess

  ai: #科大讯飞的api
    hostUrl:
    domain:
    appid:
    apiSecret:
    apiKey:
